### ISSUE TITLE
export storage & firestore in config.js

### ISSUE THREAD

**Issue by mohamedjaouda** [iamshaunjp/firegram#13]
![image 1](https://user-images.githubusercontent.com/80783601/146643298-1ed62a39-9e3b-4377-bbba-4523d4d41226.png)

**Comment by mohamedjaouda** [comment]
If You are using Version 9 then you'll want to replace " import 'firebase/storage' " with " import 'firebase/compat/storage' " as well as firestore import

**Comment by habibudurumi** [comment]
thanks man really appreciate
